# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aed47e03b417ab4383af5f57a042ff3ce29cb0ef1aad806e08fae7f6ab511d5c5f643a9b6b95290b5792fbc3f33fde8663273a154e67c24e87fee86c4154fa1

test:
  secret_key_base: 9b52cedb9c9909a1ae41c62c3334083cd6da8703ab2cdf8f7e46c23984cbb387e94e80bb8ccad5c00307aebb39d5f92b37a8d16763f1e87d3cd1e2c9d0a8470b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
